name: Github Test Action
on: [pull_request]
jobs:
  run:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: ['ubuntu-latest'] #, 'windows-latest', 'macros-latest'
        php-versions: ['8.4'] #, '8.5'
        include:
          - operating-system: 'ubuntu-latest'
            php-versions: '8.4'

    steps:
      - name: Clone Repo
        uses: actions/checkout@v5

      - name: Install Dependencies
        uses: php-actions/composer@v6
        with:
          version: "2.x"

      - name: PHPUnit tests
        uses: php-actions/phpunit@v4
        with:
          version: 13.0
          php_version: ${{ matrix.php-versions }}
          php_extensions: simplexml, xdebug
          configuration: phpunit.xml
          args: --coverage-text
        env:
          XDEBUG_MODE: coverage
